### ISSUE TITLE
When add @component('checkoutMap'), site not working.

### ISSUE THREAD

**Issue by kszere** [ryanmitchell/ti-ext-checkoutmap#1]
Copy "igniter/cart/components/checkout/address_fields.blade.php" to "_partials/checkout/address_fields.blade.php" in default theme.
Enable ext.
When I add bottom file `@component('checkoutMap')`, site not working.
Why?

**Comment by ryanmitchell** [comment]
You need to add the component to the checkout page in design -> theme

**Comment by kszere** [comment]
Here? In frontend I see "Something went wrong and the page cannot be displayed".
<img width="556" alt="Zrzut ekranu 2021-12-19 o 17 04 26" src="https://user-images.githubusercontent.com/7155051/146681833-fa7bd522-82b8-4100-b12f-06d5579576f0.png">

**Comment by ryanmitchell** [comment]
Right page but not how you did it. 

Click the + and add checkout map to register it on the page. Doesn’t need to be in the code area.

**Comment by kszere** [comment]
<img width="1052" alt="Zrzut ekranu 2021-12-19 o 17 26 34" src="https://user-images.githubusercontent.com/7155051/146682727-e368caea-00fe-4451-8052-b4889d38f12d.png">

**Comment by kszere** [comment]
Thanks. Is works!
